FrontEndProjetoFinalAtos/FrontEndProjetoFinalAtos/Controllers/CategoriaController.cs
using FrontEndProjetoFinalAtos.Models;
using FrontEndProjetoFinalAtos.ViewsModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FrontEndProjetoFinalAtos.Controllers
{
    public class CategoriaController : Controller
    {
        string BaseUrl = "http://localhost:5209/";

        public async Task<IActionResult> Index()
        {
            CategoriaViewModel model = new CategoriaViewModel();
            List<Categoria> categorias = new List<Categoria>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BaseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resposta = await client.GetAsync("categoriacontroller/categorias");

            if (resposta.IsSuccessStatusCode)
            {
                var retorno = resposta.Content.ReadAsStringAsync().Result;
                categorias = JsonConvert.DeserializeObject<List<Categoria>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + resposta.StatusCode);
            }





            model.Categorias = categorias;
            return View(model);
        }

        public async Task<IActionResult> BuscarInativas()
        {
            CategoriaViewModel model = new CategoriaViewModel();
            List<Categoria> categorias = new List<Categoria>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BaseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resposta = await client.GetAsync("categoriacontroller/categorias/inativas");

            if (resposta.IsSuccessStatusCode)
            {
                var retorno = resposta.Content.ReadAsStringAsync().Result;
                categorias = JsonConvert.DeserializeObject<List<Categoria>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + resposta.StatusCode);
            }

            model.Categorias = categorias;
            return View("Index", model);
        }

        public async Task<IActionResult> BuscarAtivas()
        {
            CategoriaViewModel model = new CategoriaViewModel();
            List<Categoria> categorias = new List<Categoria>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BaseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resposta = await client.GetAsync("categoriacontroller/categorias/ativas");

            if (resposta.IsSuccessStatusCode)
            {
                var retorno = resposta.Content.ReadAsStringAsync().Result;
                categorias = JsonConvert.DeserializeObject<List<Categoria>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + resposta.StatusCode);
            }

            model.Categorias = categorias;
            return View("Index",model);
        }

        public async Task<IActionResult> CadastrarCategoria(CategoriaViewModel model)
        {
            Categoria categoria = new Categoria();
            categoria.Nome = model.Categoria.Nome;
            HttpClient client = new HttpClient();
            HttpResponseMessage respostaPost = await client.PostAsJsonAsync(BaseUrl + "categoriacontroller/categorias", categoria);
            return RedirectToAction("Index");


        }

        public async Task<IActionResult> AtualizarCategoria(CategoriaViewModel model)
        {
            Categoria categoria = new Categoria();
            categoria.Id = model.Categoria.Id;
            categoria.Nome = model.Categoria.Nome;
            categoria.Ativo = model.Categoria.Ativo;

            HttpClient client = new HttpClient();
            HttpResponseMessage respostaPut = await client.PutAsJsonAsync(BaseUrl + "categoriacontroller/categorias/" + categoria.Id, categoria);
            return RedirectToAction("Index");




        }
    }
}

FrontEndProjetoFinalAtos/FrontEndProjetoFinalAtos/Controllers/PedidoCozinheiroController.cs
using FrontEndProjetoFinalAtos.Models;
using FrontEndProjetoFinalAtos.ViewsModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FrontEndProjetoFinalAtos.Controllers
{
    public class PedidoCozinheiroController : Controller
    {
        string BaseUrl = "http://localhost:5209/";
        

        public async Task<IActionResult> Index()
        {
            PedidoViewModel model = new PedidoViewModel();
            List<Pedido> pedidos = new List<Pedido>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BaseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage respostaPedidossEmAndamento = await client.GetAsync("pedidocontroller/pedidos/emAndamento");

            if (respostaPedidossEmAndamento.IsSuccessStatusCode)
            {
                var retorno = respostaPedidossEmAndamento.Content.ReadAsStringAsync().Result;
                pedidos = JsonConvert.DeserializeObject<List<Pedido>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + respostaPedidossEmAndamento.StatusCode);
            }

            model.Pedidos = pedidos;
            return View(model);
        }

        public async Task<IActionResult> BuscarItensPedidos(int id)
        {
            PedidoViewModel model = new PedidoViewModel();
            List<ItensPedido> itens = new List<ItensPedido>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BaseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage respostaItensPedido = await client.GetAsync("itenspedidocontroller/itenspedidos/" + id);


            if (respostaItensPedido.IsSuccessStatusCode)
            {
                var retorno = respostaItensPedido.Content.ReadAsStringAsync().Result;
                itens = JsonConvert.DeserializeObject<List<ItensPedido>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + respostaItensPedido.StatusCode);
            }

            return Json(itens);

        }

        public async Task<IActionResult> AtualizarAndamento(PedidoViewModel model)
        {
            Pedido pedido = new Pedido();
            pedido.Andamento = "preparado";

            HttpClient client = new HttpClient();
            HttpResponseMessage respostaPut = await client.PutAsJsonAsync(BaseUrl + "pedidocontroller/pedidos/" + model.Pedido.Id, pedido);
            return RedirectToAction("Index");
        }
    }
}

FrontEndProjetoFinalAtos/FrontEndProjetoFinalAtos/Controllers/ProdutoController.cs
using FrontEndProjetoFinalAtos.Models;
using FrontEndProjetoFinalAtos.ViewsModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FrontEndProjetoFinalAtos.Controllers
{
    public class ProdutoController : Controller
    {
        string BaseUrl = "http://localhost:5209/";

        public async Task<IActionResult> Index()
        {
            ProdutoViewModel model = new ProdutoViewModel();
            List<Produto> produtos = new List<Produto>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BaseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resposta = await client.GetAsync("produtocontroller/produtos");

            if (resposta.IsSuccessStatusCode)
            {
                var retorno = resposta.Content.ReadAsStringAsync().Result;
                produtos = JsonConvert.DeserializeObject<List<Produto>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + resposta.StatusCode);
            }

            
            List<Categoria> categorias = new List<Categoria>();
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage respostaCategoriaAtivas = await client.GetAsync("categoriacontroller/categorias/ativas");

            if (respostaCategoriaAtivas.IsSuccessStatusCode)
            {
                var retorno = respostaCategoriaAtivas.Content.ReadAsStringAsync().Result;
                categorias = JsonConvert.DeserializeObject<List<Categoria>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + respostaCategoriaAtivas.StatusCode);
            }

            model.Categorias = categorias;
            model.Produtos = produtos;
            return View(model);
        }

        public async Task<IActionResult> BuscarInativos()
        {
            ProdutoViewModel model = new ProdutoViewModel();
            List<Produto> produtos = new List<Produto>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BaseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resposta = await client.GetAsync("produtocontroller/produtos/inativos");

            if (resposta.IsSuccessStatusCode)
            {
                var retorno = resposta.Content.ReadAsStringAsync().Result;
                produtos = JsonConvert.DeserializeObject<List<Produto>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + resposta.StatusCode);
            }


            List<Categoria> categorias = new List<Categoria>();
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage respostaCategoriaAtivas = await client.GetAsync("categoriacontroller/categorias/ativas");

            if (respostaCategoriaAtivas.IsSuccessStatusCode)
            {
                var retorno = respostaCategoriaAtivas.Content.ReadAsStringAsync().Result;
                categorias = JsonConvert.DeserializeObject<List<Categoria>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + respostaCategoriaAtivas.StatusCode);
            }

            model.Categorias = categorias;
            model.Produtos = produtos;
            return View("Index",model);
        }

        public async Task<IActionResult> BuscarAtivos()
        {
            ProdutoViewModel model = new ProdutoViewModel();
            List<Produto> produtos = new List<Produto>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(BaseUrl);
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage resposta = await client.GetAsync("produtocontroller/produtos/ativos");

            if (resposta.IsSuccessStatusCode)
            {
                var retorno = resposta.Content.ReadAsStringAsync().Result;
                produtos = JsonConvert.DeserializeObject<List<Produto>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + resposta.StatusCode);
            }

            List<Categoria> categorias = new List<Categoria>();
            client.DefaultRequestHeaders.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage respostaCategoriaAtivas = await client.GetAsync("categoriacontroller/categorias/ativas");

            if (respostaCategoriaAtivas.IsSuccessStatusCode)
            {
                var retorno = respostaCategoriaAtivas.Content.ReadAsStringAsync().Result;
                categorias = JsonConvert.DeserializeObject<List<Categoria>>(retorno);
            }
            else
            {
                Console.WriteLine("Erro: " + respostaCategoriaAtivas.StatusCode);
            }

            model.Categorias = categorias;
            model.Produtos = produtos;
            return View("Index", model);
        }

        public async Task<IActionResult> CadastrarProduto(ProdutoViewModel model)
        {
            Produto produto = new Produto();
            produto.Nome = model.Produto.Nome;
            produto.Valor = model.Produto.Valor;
            produto.FkCategoria = model.Produto.FkCategoria;
          

            HttpClient client = new HttpClient();
            HttpResponseMessage respostaPost = await client.PostAsJsonAsync(BaseUrl + "produtocontroller/produtos", produto);
            return RedirectToAction("Index");
        }

         public async Task<IActionResult> AtualizarProduto(ProdutoViewModel model)
        {
            Produto produto = new Produto();
            produto.Id = model.Produto.Id;
            produto.Nome = model.Produto.Nome;
            produto.Valor = model.Produto.Valor;
            produto.FkCategoria = model.Produto.FkCategoria;
            produto.Ativo = model.Produto.Ativo;

            HttpClient client = new HttpClient();
            HttpResponseMessage respostaPut = await client.PutAsJsonAsync(BaseUrl + "produtocontroller/produtos/" + produto.Id, produto);
            return RedirectToAction("Index");
        }

    }
}

FrontEndProjetoFinalAtos/FrontEndProjetoFinalAtos/Views/PedidoCozinheiro/Index.cshtml
@using FrontEndProjetoFinalAtos.ViewsModels;
@model PedidoViewModel


@{

    Layout = null;
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/css/PedidoCozinheiro/pedido-cozinheiro.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300&display=swap" rel="stylesheet">

</head>


<body>

    <nav  class=" navbar navbar-expand-lg">
        <div id="box-nav"  class="container-fluid">
            <a id="a-nav" class="navbar-brand" href="#"></a>
            <button id="button-nav" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <img id="img-nav" alt="menu" src="~/img/menubar.svg" />
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a id="a-nav" class="nav-link active" aria-current="page" asp-controller="Categoria" asp-action="Index">Categoria</a>
                    </li>
                    <li class="nav-item">
                        <a id="a-nav" class="nav-link" asp-controller="Produto" asp-action="Index">Produto</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>



    <div id="box-pedidos">
        <h1>PEDIDOS</h1>

        @if (Model.Pedidos != null && Model.Pedidos.Count > 0)
        {
            <ul id="ul-box-pedidos">

                @foreach (var pedido in Model.Pedidos)
                {
                    <li id="li-box-pedidos">

                        <p id="p-li">Mesa @pedido.Mesa</p>
                        <button onclick="dadosModal(@pedido.Mesa,@pedido.Id)" class="button-detalhes" data-bs-toggle="modal" data-bs-target="#exampleModal">Detalhes</button>
                    </li>
                }
                
           

        </ul>
        }

        else
        {

            
           
            <p id="p-nenhumPedido">NENHUM PEDIDO NO MOMENTO.</p>
            
            
        }


    </div>



    <img id="img-elipse" src="~/img/Elipse.svg">


    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="box-modal-header">
                    <h5 class="modal-titulo">PEDIDO<span id="titulo-id"></span></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <form method="post" asp-action="AtualizarAndamento">
                    <div class="box-modal-body">

                        <p id="p-modal"></p>
                        <input asp-for="Pedido.Id" id="id-pedido-modal" type="hidden" />

                    <ul id="lista-dados">

                        </ul>
                        
                    </div>
                    <div class="box-modal-footer">
                        <button type="button" class="button-cancelar-modal" data-bs-dismiss="modal">Cancelar</button>



                        <button type="submit" class="button-preparado-modal">Pedido preparado</button>
              
                    </div>
                </form>
        </div>
    </div>

    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/PedidoCozinheiro/pedido-cozinheiro.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>